CREATE TABLE public.product_family (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	models_available int4 NULL,
	company_manufacturer varchar(255) NULL,
	country_manufacturer varchar(255) NULL,
	family_name varchar(255) NULL,
	buy_online bool NOT NULL,
	installment bool NOT NULL,
	product_type varchar(255) NOT NULL,
	CONSTRAINT product_family_pkey PRIMARY KEY (id)
);
CREATE INDEX idx29jn9iq1wp9frv62s04373vhb ON public.product_family USING btree (family_name);

CREATE TABLE public.products (
	"type" varchar(31) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	model_available bool NULL,
	model_color varchar(255) NULL,
	model_name varchar(255) NULL,
	model_price numeric(19, 2) NULL,
	model_serial varchar(255) NULL,
	model_size varchar(255) NULL,
	product_type varchar(255) NULL,
	model_volume float4 NULL,
	model_modes varchar(255) NULL,
	model_compressor varchar(255) NULL,
	model_doors int4 NULL,
	model_category varchar(255) NULL,
	model_processor varchar(255) NULL,
	model_camera varchar(255) NULL,
	model_memory int4 NULL,
	model_technology varchar(255) NULL,
	family_id int8 NULL,
	CONSTRAINT products_pkey PRIMARY KEY (id),
	CONSTRAINT fk1vp91avmgsoc34e5p9s4142dl FOREIGN KEY (family_id) REFERENCES public.product_family(id)
);
CREATE INDEX idx9fhnf7qq5v9g7tbebqnqg1065 ON public.products USING btree (model_name);