CREATE TABLE public.product_family (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	models_available int4 NULL,
	company_manufacturer varchar(255) NULL,
	country_manufacturer varchar(255) NULL,
	family_name varchar(255) NULL,
	buy_online bool NOT NULL,
	installment bool NOT NULL,
	product_type varchar(255) NOT NULL,
	CONSTRAINT product_family_pkey PRIMARY KEY (id)
);
CREATE INDEX idx29jn9iq1wp9frv62s04373vhb ON public.product_family USING btree (family_name);